---
- name: Run kubectl apply
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Apply Deployment YAML
      command: sudo kubectl apply -f k8s/deploy.yaml

    - name: Apply Service YAML
      command: sudo kubectl apply -f k8s/service.yaml
