apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: abctechnologies-app
  name: abctechnologies-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32002
  selector:
    app: abctechnologies-app
  type: NodePort
status:
  loadBalancer: {}
